name: The Grid
favicon: 'https://passport.thegrid.io/favicon.ico'
layout_spectrum: 0.5
typography_spectrum: 0.5
style: A1
collections:
  - filter:
      notTag:
        tag: ancillary
    index:
      path: /
      number: 50
      navigable: true
  - filter:
      tag:
        tag: ancillary
    permalink:
      path: '/:title/'
      navigable: true
  - filter:
      tag:
        tag: team
    permalink:
      path: /team/
      navigable: true
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
color:
  brandColors:
    - '#a6816f'
    - '#0d3151'
    - '#0b7872'
    - '#d1433f'
    - '#5c585e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
